networks:
  inner:
    driver: bridge

services:
  registry-server:
    image: registry:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./data:/var/lib/registry:rw
      - ./config/server/config.yml:/etc/docker/registry/config.yml:ro
    container_name: registry-server
    networks:
      - inner
  registry-gui:
    image: joxit/docker-registry-ui:main
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=false
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-gui
    depends_on:
      - registry-server
    networks:
      - inner
