networks:
  inner:
    driver: bridge

services:
  registry-server:
    image: registry:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "[HEAD,GET,OPTIONS]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: "[true]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "[Authorization,Accept,Cache-Control]"
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: "[Docker-Content-Digest]"
      REGISTRY_STORAGE_DELETE_ENABLED: "false"
      REGISTRY_LOG_LEVEL: "debug"
    volumes:
      - ./data:/var/lib/registry:rw
      - ./config/server/config.yml:/etc/docker/registry/config.yml:ro
    container_name: registry-server
    networks:
      - inner
  registry-admin:
    restart: unless-stopped
    image: zebox/registry-admin:master
    ports:
      - 1091:80
    environment:
      - RA_CONFIG_FILE=/app/config/token-ra-config.yml
    volumes:
      - ./certs:/app/certs
      - ./config:/app/config
      - ./data:/app/data
