networks:
  inner:
    driver: bridge

services:
  proxy-registry:
    image: registry:2
    container_name: proxy-registry
    expose:
      - "5000"
    volumes:
      - ./data:/var/lib/registry:rw
      - ./config/server/proxy-config.yml:/etc/docker/registry/config.yml:ro
    restart: always
    networks:
      - inner
  local-registry:
    image: registry:2
    container_name: local-registry
    expose:
      - "5000"
    volumes:
      - ./data:/var/lib/registry:rw
      - ./config/server/local-config.yml:/etc/docker/registry/config.yml:ro
    restart: always
    networks:
      - inner
  nginx:
    image: nginx:latest
    container_name: registry-nginx
    ports:
      - "5000:5000"
    volumes:
      - ./config/nginx/config.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - local-registry
      - proxy-registry
    networks:
      - inner
  registry-gui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 80:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=false
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://nginx:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-gui
    depends_on:
      - nginx
    networks:
      - inner
