version: 0.1
proxy:
  remoteurl: https://registry-1.docker.io
log:
  level: debug
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
notifications:
  events:
    includereferences: true
